/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as BrandContentSocialPortfolioRouteImport } from './routes/brand-content-social-portfolio'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as PerformanceMarketingResultsRouteImport } from './routes/performance-marketing-results'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TechnologySoftwarePortfolioRouteImport } from './routes/technology-software-portfolio'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandContentSocialPortfolioRoute =
  BrandContentSocialPortfolioRouteImport.update({
    id: '/brand-content-social-portfolio',
    path: '/brand-content-social-portfolio',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceMarketingResultsRoute =
  PerformanceMarketingResultsRouteImport.update({
    id: '/performance-marketing-results',
    path: '/performance-marketing-results',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologySoftwarePortfolioRoute =
  TechnologySoftwarePortfolioRouteImport.update({
    id: '/technology-software-portfolio',
    path: '/technology-software-portfolio',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/brand-content-social-portfolio': typeof BrandContentSocialPortfolioRoute
  '/contact-us': typeof ContactUsRoute
  '/performance-marketing-results': typeof PerformanceMarketingResultsRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/technology-software-portfolio': typeof TechnologySoftwarePortfolioRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/brand-content-social-portfolio': typeof BrandContentSocialPortfolioRoute
  '/contact-us': typeof ContactUsRoute
  '/performance-marketing-results': typeof PerformanceMarketingResultsRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/technology-software-portfolio': typeof TechnologySoftwarePortfolioRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/brand-content-social-portfolio': typeof BrandContentSocialPortfolioRoute
  '/contact-us': typeof ContactUsRoute
  '/performance-marketing-results': typeof PerformanceMarketingResultsRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRoute
  '/technology-software-portfolio': typeof TechnologySoftwarePortfolioRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/brand-content-social-portfolio'
    | '/contact-us'
    | '/performance-marketing-results'
    | '/portfolio'
    | '/services'
    | '/technology-software-portfolio'
    | '/terms-and-conditions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/brand-content-social-portfolio'
    | '/contact-us'
    | '/performance-marketing-results'
    | '/portfolio'
    | '/services'
    | '/technology-software-portfolio'
    | '/terms-and-conditions'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/brand-content-social-portfolio'
    | '/contact-us'
    | '/performance-marketing-results'
    | '/portfolio'
    | '/services'
    | '/technology-software-portfolio'
    | '/terms-and-conditions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  BrandContentSocialPortfolioRoute: typeof BrandContentSocialPortfolioRoute
  ContactUsRoute: typeof ContactUsRoute
  PerformanceMarketingResultsRoute: typeof PerformanceMarketingResultsRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRoute
  TechnologySoftwarePortfolioRoute: typeof TechnologySoftwarePortfolioRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-content-social-portfolio': {
      id: '/brand-content-social-portfolio'
      path: '/brand-content-social-portfolio'
      fullPath: '/brand-content-social-portfolio'
      preLoaderRoute: typeof BrandContentSocialPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance-marketing-results': {
      id: '/performance-marketing-results'
      path: '/performance-marketing-results'
      fullPath: '/performance-marketing-results'
      preLoaderRoute: typeof PerformanceMarketingResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology-software-portfolio': {
      id: '/technology-software-portfolio'
      path: '/technology-software-portfolio'
      fullPath: '/technology-software-portfolio'
      preLoaderRoute: typeof TechnologySoftwarePortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  BrandContentSocialPortfolioRoute: BrandContentSocialPortfolioRoute,
  ContactUsRoute: ContactUsRoute,
  PerformanceMarketingResultsRoute: PerformanceMarketingResultsRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRoute,
  TechnologySoftwarePortfolioRoute: TechnologySoftwarePortfolioRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
